### ISSUE TITLE
Upload to maven central

### ISSUE THREAD

**Issue by yoavst** [LGDeveloper/QCircle-Design-Template#1]

**Comment by lyingdragon** [comment]
The library (an AAR file) is uploaded to maven central repository.
Visit https://github.com/LGDeveloper/QCircle-Design-Template.git

**Comment by yoavst** [comment]
hi @LGDeveloper can you upload the latest version?

**Comment by lyingdragon** [comment]
We're going to upload it in this week or the next week. Please give a second. :)

**Comment by lyingdragon** [comment]
Hi @yoavst. The latest version has been uploaded!
Visit [here](http://search.maven.org/#artifactdetails%7Ccom.lge.developer%7Cqcircle-design-template%7C2.0.0%7Caar).

**Comment by yoavst** [comment]
so can you upload it to github releases?  I could use `jitpack` than.

**Comment by lyingdragon** [comment]
Done.
