### ISSUE TITLE
Remove theme and label from manifest of library

### ISSUE THREAD

**Issue by yoavst** [LGDeveloper/QCircle-Design-Template#10]
Error:(35, 9) Attribute application@label value=(@string/app_name) from AndroidManifest.xml:35:9
Error:(36, 9) Attribute application@theme value=(@style/AppTheme) from AndroidManifest.xml:36:9
	is also present at com.lge.developer:qcircle-design-template:1.0.0:14:9 value=(@style/LibTheme)
	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:33:5 to override

**Comment by LGDeveloper** [comment]
I have deleted a label and theme value in AndroidManifest file in QCircle Design Template.
