### ISSUE TITLE
New back button drawable

### ISSUE THREAD

**Issue by yoavst** [LGDeveloper/QCircle-Design-Template#11]
as in 20h.

**Comment by LGDeveloper** [comment]
? Do you want me to update the back button?

**Comment by yoavst** [comment]
as in new 20h quick circle apps. It got the same look as lollipop default back button.

**Comment by LGDeveloper** [comment]
I got it but it looks like our UI & UX designers decided to maintain old back button styles. I don't exactly know why. I will update it later when it is approved by our designers. Thanks!

**Comment by yoavst** [comment]
Is there an update?

**Comment by lyingdragon** [comment]
We're checking it. I will update when I have an answer from designers.

**Comment by lyingdragon** [comment]
Back button in QuickCircle is fixed. It is same as the previous one except circular background image. 
So I think we do not need to update the icon.
