### ISSUE TITLE
Please, update QDialer for the updated library.

### ISSUE THREAD

**Issue by LGDeveloper** [LGDeveloper/QCircle-Design-Template#14]
Some methods are deprecated and updated. Please, update the QDialer for the updated library.

**Comment by yoavst** [comment]
for who is this issue?

**Comment by LGDeveloper** [comment]
I was trying to assign it to you  but i wasnt able to dee you on the list.
Would you update the qdialer?

**Comment by yoavst** [comment]
Yea, I'm bit short on time, so I'll do it next week. next time post it on my repo :)

**Comment by yoavst** [comment]
what is the alternative to the deprecated method `setBackgroundColor`?

**Comment by yoavst** [comment]
Done. See my notes. I'll send a pull request soon.

**Comment by yoavst** [comment]
@LGDeveloper I've finished it.

**Comment by lyingdragon** [comment]
OK, Thanks!
