### ISSUE TITLE
List of supported device

### ISSUE THREAD

**Issue by yoavst** [LGDeveloper/QCircle-Design-Template#19]
It will be very nice if there will be an official list of devices support Quick Circle, so we could use it for LG SmartWorld and Play Store listing.

**Comment by lyingdragon** [comment]
The list is given at [Supported Devices](http://developer.lgmobile.com/MOBILE_HELP/index.jsp?topic=%2Flge.mobilesdk.lgqcircle.api%2FDocuments%2Fsupporteddevices.htm) in LG QCircle Developer Guide.

**Comment by yoavst** [comment]
> •  LG G3 series: LG G3, LG G3 beat, LG G3 Cat 6 and more.
> •  LG G4

It isn't updated (for example, Flex 2), and it will be really useful if it will say their model number also (since for example the G3 itself is D855, D850, D851, D852, D857...)

**Comment by lyingdragon** [comment]
I'll ask the person in charge whether it's possible to provide model number.

**Comment by lyingdragon** [comment]
We will list the supported devices in http://developer.lge.com/resource/mobile/RetrieveOverview.dev?categoryTypeCode=ANRS#RS00000829. In addition, the person in charge said that she cannot list all of the model numbers which has a Quick Circle because there are too many models.
