### ISSUE TITLE
Circle Case Timeout

### ISSUE THREAD

**Issue by sp70** [LGDeveloper/QCircle-Design-Template#22]
Is there a method in which to adjust the Circle Case timeout value?

3 seconds is rather short.

Adding an option for a configurable variable or even a list of timeout options that includes 'never' would be nice.

**Comment by lyingdragon** [comment]
No, there's isn't.
By the way, what is the timeout value? The lcd-on duration time after the case is closed?

**Comment by sp70** [comment]
I don't know where to find that value, but just watching the screen upon closing the case, it appears to display the clock for about 5 seconds, and then fades to black.

**Comment by yoavst** [comment]
The only other way is to set the screen to always on.

**Comment by lyingdragon** [comment]
The lcd-on time is determined by Quick Circle framework. We cannot adjust it.
