### ISSUE TITLE
Memory footprint

### ISSUE THREAD

**Issue by yoavst** [LGDeveloper/QCircle-Design-Template#23]
Let's says we've got a regular activity:
```java
public class LeakActivity extends AppCompatActivity {
   @Override
    public void onStart() {
        super.onStart();
       new QCircleTemplate(this, TemplateType.CIRCLE_EMPTY);
    }
}
```
In normal situation the memory usage will be as before, but currently:
![img](http://i.imgur.com/kdzw98h.png)

I'll try to research it by myself.

Referencing issue in my repo: https://github.com/yoavst/quickapps/issues/1

Edit 1:
The memory goes high on:
```java
layoutView = ((Activity)this.mContext).getLayoutInflater().inflate(layout.qcircle_empty, (ViewGroup)null);
```

Edit 2:
**The fix is simple, moving `circlebackground.png` drawable to drawable-nodpi fixes it. I've checked it on LG G4 and it looks the same.**

**Comment by lyingdragon** [comment]
Fixed. See f3503c3ddea9c623d253ca8b878ef525d8ccf295
